#!/bin/sh
#
# Automatically add branch name and branch description to every commit message except merge commit.
#

COMMIT_EDITMSG=$1

commitEmoji() {
  h=$(date +%H)

  if [$h -lt 5]; then
    echo ":sleeping:"
  elif [$h -lt 11]; then
    echo ":coffee:"
  elif [$h -lt 15]; then
    echo ":surfer:"
  elif [$h -lt 21]; then
    echo ":tada:"
  else
    echo ":new_moon_with_face:"
  fi
}

addBranchName() {
  NAME=$(git branch | grep '*' | sed 's/* //')
  DESCRIPTION=$(git config branch."$NAME".description)
  echo "[$NAME]: $(cat $COMMIT_EDITMSG)" > $COMMIT_EDITMSG
  if [ -n "$DESCRIPTION" ]
  then
     echo "" >> $COMMIT_EDITMSG
     echo $DESCRIPTION >> $COMMIT_EDITMSG
  fi
}

MERGE=$(cat $COMMIT_EDITMSG|grep -i 'merge'|wc -l)
commitEmoji
if [ $MERGE -eq 0 ] ; then
  addBranchName
fi
