#!/bin/sh
#
# Automatically add branch name and branch description to every commit message except merge commit.
#

COMMIT_EDITMSG=$1

addBranchName() {
  NAME=$(git branch | grep '*' | sed 's/* //')
  echo ":upside_down_face: $(cat $COMMIT_EDITMSG)" > $COMMIT_EDITMSG
  echo "" >> $COMMIT_EDITMSG
  echo "[$NAME]" >> $COMMIT_EDITMSG
}

MERGE=$(cat $COMMIT_EDITMSG|grep -i 'merge'|wc -l)

if [ $MERGE -eq 0 ] ; then
  addBranchName
fi
